#ifndef EFFECTIVE_BROCOLLI_ERROR_CODES
#define EFFECTIVE_BROCOLLI_ERROR_CODES

enum Error {
  NO_ERROR = 0,
  FALSE_TYPE,
  CTOR_FAILED,
  BAD_PTR,
  ALREADY_DELETED,
  OUT_OF_BOUNDS,
  OBJECT_NOT_PRESENT,
  NOT_FOUND,
  ALLOC_FAILED
};

#endif